package com.dimacofi.DAO;
// Generated 20-03-2019 16:10:13 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;




/**
 * NomUsr generated by hbm2java
 */
public class NomUsr  implements java.io.Serializable {

  private short idUser;
    private String nombres;
    
    
    @ManyToOne
   // @JsonView(Rol.class)
    @JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
    @JoinColumn(name = "rol")
    private Rol rol;

    @JsonIgnore
    @OneToMany(mappedBy = "users")
    private Users users;

    public NomUsr() {
    }

    public NomUsr(Rol rol, Users users, String nombres) {
       this.rol = rol;
       this.users = users;
       this.nombres = nombres;
    }
   
    public short getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(short idUser) {
        this.idUser = idUser;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }




}


