package com.dimacofi.DAO;
// Generated 20-03-2019 16:10:13 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonIgnore;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.OneToMany;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


   
     private short idRol;
     private String descripcion;
     
     @JsonIgnore
     @OneToMany(mappedBy="nomUsrs")
     private Set nomUsrs = new HashSet(0);

    public Rol() {
    }

	
    public Rol(short idRol) {
        this.idRol = idRol;
    }
    public Rol(short idRol, String descripcion, Set nomUsrs) {
       this.idRol = idRol;
       this.descripcion = descripcion;
       this.nomUsrs = nomUsrs;
    }
   
    public short getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(short idRol) {
        this.idRol = idRol;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getNomUsrs() {
        return this.nomUsrs;
    }
    
    public void setNomUsrs(Set nomUsrs) {
        this.nomUsrs = nomUsrs;
    }




}


