package com.dimacofi.DAO;
// Generated 20-03-2019 16:10:13 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.OneToOne;




/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


    private short idUser;
     private String userName;
     private String password;
     
     @JsonIgnore
     @OneToOne(mappedBy="nomUsr")
     private NomUsr nomUsr;


    public Users() {
    }

	
    public Users(short idUser) {
        this.idUser = idUser;
    }
    public Users(short idUser, String userName, String password, NomUsr nomUsr) {
       this.idUser = idUser;
       this.userName = userName;
       this.password = password;
       this.nomUsr = nomUsr;
    }
   
    public short getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(short idUser) {
        this.idUser = idUser;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public NomUsr getNomUsr() {
        return this.nomUsr;
    }
    
    public void setNomUsr(NomUsr nomUsr) {
        this.nomUsr = nomUsr;
    }




}


